# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('definition', models.TextField(blank=True)),
                ('language', models.CharField(max_length=25)),
                ('antonyms', models.ManyToManyField(blank=True, related_name='_word_antonyms_+', to='dictionary.Word')),
                ('synonyms', models.ManyToManyField(blank=True, related_name='_word_synonyms_+', to='dictionary.Word')),
                ('translaions', models.ManyToManyField(blank=True, related_name='_word_translaions_+', to='dictionary.Word')),
            ],
        ),
    ]
